
services:
  backend:
    build: .
    container_name: demo_backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env  # Load environment variables from a .env file
    volumes:
      - .:/src  # Mount the current directory to /src in the container
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-tier
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    container_name: demo_redis
    ports:
      - "6379:6379"
    networks:
      - app-tier

  postgres:
    image: postgres:latest
    container_name: demo_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-tier

volumes:
  postgres_data:
    driver: local

networks:
  app-tier:
    driver: bridge
